
services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      ## Static Configuration file
      - "--configFile=/etc/traefik/traefik.yaml"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      ## Static Config
      - "./traefik.yaml:/etc/traefik/traefik.yaml:ro"
      ## Dynamic Config
      - "./rules:/rules"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-net

networks:
  traefik-net:
    name: traefik-net
    driver: bridge
