http:
  routers:
    whoami:
      rule: "Host(`whoami.localhost`)"
      entryPoints:
        - web
        - websecure
      service: whoami
    outline:
      rule: "Host(`outline.localhost`)"
      entryPoints:
        - web
        # - websecure
      service: outline

